package edu.adriennicholas.atm.util;

public enum EventType {
	LOGIN_ATTEMPT, LOGIN_BLOCKED, LOGIN_INVALID, LOGIN_SUCCESS, LOGIN_FAILED, LOGOUT_REQUEST, SHOW_PANEL, USER_ADDED, TRANSACTION_COMPLETED

}
